markdown: rdiscount
pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]
title : Curtis Pond
production_url : http://curtpond.com
description: "A little bit of everything"
disqus_shortname: false
CNAME: curtpond.com
analytics: false
gauges: false
author :
  name : Curtis Pond
  github : curtpond
  twitter : curtpond
  linkedin: http://www.linkedin.com/in/curtispond
  email: curtis.pond@gmail.com
